### ISSUE TITLE
Several typo's

### ISSUE THREAD

**Issue by janbaltussen** [thosgood/qubit.guide#12]
Dear Tim,

(I edited this issue, because on re-reading it, I found out, that I can use Latex....).

I studied your Intro to Quantum Information Science - the first part - Foundations.
Great book, I like it very much, especially in combination with the Youtube movies.
And I like the way density operators are introduced and explained - and the exposee on quantum operations. Great!

I found a few typo's, most of them innocent. However 7.9 has some problems (I think), that took me quite some while. It's not so long ago, that I started studying quantum theory, so I assumed my calculations were the problem. On the other hand, this quest gave me a better understanding of the tensor product. (So in a way, I am grateful for the current version of 7.9, for this tensor product concept is quite a thing!)

0.1 Formula at the end of the alternative formula for $1/(x+iy)$: $(x/x^2 + y^2) - i(y/x^2 + y^2)$
	$x+2$ in the text should be $x^2$

1.2.1 Double-slit 
	Shouldn't you explicitly mention, that this 'particle emitted' is a quantum particle (e.g. photon)?

4.4 Example of an incomplete measurement
'...Ideally, we would like to perform a complete measurement that would resolve the state $\ket{v}$ into the ...'
	Typo: $\ket{v}$ should be $\ket{\psi}$

5.8 Why qubits, subsystems, and entanglement?
'...units of energy to to switch a physical bit from...'
	Typo: to to -> to

6.1 Definitions (Density matrices)
'...where $p1, p2 >=$ are such that...'
	Typo: $p1, p2 >= 0$

7.1 Everything is (secretly) unitary
'...of the auxiliary system in not correlated...'
	Typo: in -> is

7.4 Evolution of open systems
Remark to the movies:
The movie 'Expand, evolve, reduce' of 7.4 alligns better as first introducing movie for 7.7, it covers the first part of the exposee of 7.7. The existing movie for 7.7 is ok (as a second movie - it covers the second part of 7.7's argument).

7.5 Stinespring’s dilation and Kraus’s ambiguity
Remark to the movies:
The second movie for 7.5. is an overview of Kraus, Stinespring and Choi.
Choi is only covered in 7.9, so shouldn't it be part of 7.9?

7.9 Channel-state duality

1.
Formula, marked by (#):
Running index i in the last part of the formula should be ij.

2.
Shouldn't the first introduction (immediately after the formula (#) of the Choi-matrix have a factor $\frac{1}{d}$?
Everywhere else in 7.9 it looks like this factor is part of the definition of the Choi-matrix.

3.
After '...If we take $A$ and $B$ to be the block matrices $\rho \otimes \mathbf{1}$ respectively, then we can use this to show that...': Running index i should be ij

Remark:
'...Now the formula in the first blue window indeed looks baffling...'
Indeed. For me the approach to understand the formula was the following.
$( A \otimes \mathbf{1} ) B$ represents $B$ in blocks of the size of $\mathbf{1}$, and the elements of $A$ multiply these blocks (number $\times$ matrix).
And in the same way - $tr$ is also a linear operator - $(tr \otimes \mathbf{1}) B$ represents $B$ in blocks of the size of $\mathbf{1}$, and then $tr \otimes \mathbf{1}$ operates on $B$, that is: takes the matrix-sum of the diagonal blocks.
For me the first part $tr \otimes \mathbf{1}$ was the most intriguing. 
If I am correct, $(tr \otimes \mathbf{1}) B = \sum_i \ket{i \otimes \mathbf{1}} B \bra{i \otimes \mathbf{1}}$?

4.
After 'acting on the maximally mixed state $\Omega$...'
Shouldn't factor $\frac{1}{d}$ in $\Omega$ be deleted (even if that leaves $\Omega$ not-normalized)? 
Shouldn't factor $\frac{1}{d}$ pop-up in the formula for the Choi-matrix $\tilde{\mathcal{E}}$: $(\mathbf{1} \otimes \mathcal{E}) \frac{1}{d} \bra{\Omega}\ket{\Omega}$?
If so, the formula's a bit further below, '...whence $\tilde{\mathcal{E}}$ ... is a density matrix, since $\ket{\Omega} \bra{\Omega}$...' should be updated too.

5.
'...Finally, $tr \mathcal{E} = 1$ implies that $\sum_k E_k^\dagger E_k = 1$...'
Shouldn't this be: $tr \mathcal{E} \rho = 1$ - the factor $\rho$ is missing?

7.10
First formula: I guess a summation fails - is this notation Einstein's shorthand (I read that elsewhere)?

**Comment by thosgood** [comment]
Hi Jan,

First of all, thank you so much for spotting all these typos! I've made a list and will fix them in the next update later this week. Let me just respond to a few of them (in reverse order), but note that I could be mistaken, so I'm happy to carry on the conversation if you don't agree!

- The first formula in §7.10 doesn't have a sum in it: it tells you what happens to an element of the form $|i\rangle\langle j|$, and the $\delta_{ij}$ term is the Kronecker delta (equal to 1 if $i=j$ and equal to 0 if $i\neq j$).
- Unless I'm misreading it, we do mean $\operatorname{tr}\widetilde{\mathcal{E}}=1$ towards the end of the proof of channel–state duality. We're assuming that the Choi matrix $\widetilde{\mathcal{E}}$ is a density operator (and trying to show that then $\mathcal{E}$ is a quantum channel), which means, in particular, that its trace is equal to 1.
- By (our choice of) definition, the maximally mixed state is normalised, so really does deserve to have a $\frac{1}{d}$ term in front of it. This is one particularly nice thing about this expression $\widetilde{\mathcal{E}}=(1\otimes\mathcal{E})|\Omega\rangle\langle\Omega|$ for the Choi matrix: it gives the $\frac{1}{d}$ term some "geometric" meaning, as the normalisation of the maximally mixed state!
- One important property of tensor products, when looking at an equation like $d(\operatorname{tr}\otimes1)[(\rho^T\otimes1)\widetilde{\mathcal{E}}]$, is that, if $f\colon V\to W$ and $g\colon Y\to Z$ are linear operators, then $(f\otimes g)\colon V\otimes Y\to W\otimes Z$ satisfies $(f\otimes g)(v\otimes y)=f(v)\otimes g(w)$. Here, the two "1"s that appear in the equation are really distinct (and I'm going to change the notation to make this clearer), since the second one is the $(d'\times d')$ identity matrix (which is a map $\mathcal{H}\to\mathcal{H}$), but the first one is the "do nothing" linear operator (which is a map $\mathcal{B}(\mathcal{H'})\to\mathcal{B}(\mathcal{H}')$ ). Of course, every linear operator can be written as a matrix, but here that's maybe not so helpful: it's nice to think of $\operatorname{tr}\otimes1$ as "just" the operator that just takes the trace on the first part of a tensor product and does nothing on the second. You can write this out as a matrix, but it's maybe helpful to try to distinguish between the two uses of "1" here. (I might actually try to go through the entire book and be a bit more consistent, choosing to write $\mathrm{id}$ vs. $1$, but I'll first have a think about how helpful that would actually be).

**Comment by janbaltussen** [comment]
Hi Tim,

I enclosed my calculations, the basis for my remarks (because the algebra must also play the game). The txt is actually the Latex source for the pdf. I am not allowed to upload a .tex file, that's why.
Where did I go wrong?
About the point $\operatorname{tr}\tilde{\mathcal{E}}=1$ : see my notes (at the end). I made a typo myself there - where I refer to Nielsen/Chuang. (I have not studied this 'bible' yet, but it is on my list). If I may say so - I like your book more (its less algebraic, it is much more on transferring understanding).

Kind regards, Jan

[7.9.txt](https://github.com/thosgood/qubit.guide/files/10060335/7.9.txt)
[7.9.pdf](https://github.com/thosgood/qubit.guide/files/10060314/7.9.pdf)

**Comment by janbaltussen** [comment]
Hi Tim,

Related to my point 4. (7.9): Defining $\Omega = \frac{1}{\sqrt{d}} \sum_i \ket{i} \otimes \ket{i}$ brings the solution!
(As an example: $\frac{1}{\sqrt{2}} \left( \ket{00} + \ket{11} \right)$ is a normalized state).
Now it fits: the density operator has factor $\frac{1}{d}$.

In the newest version of the qubit-guide, you stil use the symbol $\tilde{\mathcal{E}}$ when you introduce the block-matrix (without factor $\frac{1}{d}$. In the next sentence you redefine $\mathcal{E}$ immediately with this factor. Bit confusing? Maybe it is better, to introduce the blockmatrix without a label?

Leaves me only one problem - my point 5. (I guess, my reference to Nielsen/Chuang is irrelevant; not only that, I think that my proof is also bollocks...)

**Comment by thosgood** [comment]
Oh you're right, I should have written $\frac{1}{\sqrt{d}}$ instead of $\frac{1}{d}$ — I'll go fix that now!

As for your point 5, I think that the Nielsen & Chuang reference is maybe not the most useful, since they don't introduce the Choi matrix in that section (actually, I'm not sure if the Choi matrix appears anywhere there... I'll have to find my copy and have a look). Let me speak to Artur and figure out a good way of explaining some more details of how you go from $\operatorname{tr}\widetilde{\mathcal{E}}=1$ to $\sum_k E_k^\dagger E_k=\mathrm{id}$.

**Comment by thosgood** [comment]
OK, I've added a small hint to the exercise, which I'll repeat here (just because the web version takes some time to update).

It's helpful to note that the trace can be decomposed into a partial trace followed by a "full" trace: in particular, $\operatorname{tr}\widetilde{\mathcal{E}}=\operatorname{tr}[(\operatorname{tr}\otimes1)\widetilde{\mathcal{E}}]$. (This follows from the fact that $(\operatorname{tr}\otimes1)(A\otimes B)=(\operatorname{tr}A)B$.)
