### ISSUE TITLE
Confusing text on vector spaces

### ISSUE THREAD

**Issue by prakity** [thosgood/qubit.guide#18]
<img width="1366" alt="0 2 Euclidean vectors and vector spaces  Introduction to Quantum Information Science png" src="https://user-images.githubusercontent.com/1106259/222268365-b9a86e34-905a-4c23-b1c0-2abf97393a21.png">

use of v sub i in summation is confusing. V sub i is a number and can be confused as a component of ket v. See phrase. 

can be written (in exactly one way) as a linear combination of the basis vectors:

better to use another letter 
<img width="1366" alt="0 2 Euclidean vectors and vector spaces  Introduction to Quantum Information Science png" src="https://user-images.githubusercontent.com/1106259/222269379-73d8618f-9378-487b-a813-d7961d53760a.png">

**Comment by thosgood** [comment]
This confusion is very well justified, but it's also somewhat classical/intentional! Note that, if we write $|v\rangle$ in the usual "coordinates" way, then in the basis $e_i$ it is exactly true that $|v\rangle=(v_1,\ldots,v_n)$, and so the numbers $v_i$ *are* the components of $|v\rangle$. However, I agree that this could be better explained, so I'll write a few more sentences about this :-)

**Comment by prakity** [comment]
Hi Tim,

Just adding a note that the Vi are numbers (not vector components) would probably work just fine. 

IPaw Powered
